### ISSUE TITLE
Add official support (and update acceptance tests) for Ubuntu 16.04

### ISSUE THREAD

**Issue by wyardley** [voxpupuli/puppet-rabbitmq#622]
- [x] [semi-related] Fix some issues with local spec tests #620 
- [x] fix fixtures #619 
- [x] Add `packages_ensure` for python #623
- [ ] Switch to camptocamp systemd module (if possible - may need to work around test failures and do this later)
- [x] Update metadata and acceptance tests #624

**Comment by wyardley** [comment]
I'm going to table camptocamp systemd module for now; it adds an additional dependency, and yet doesn't yet support managing file limits the way we need to (it doesn't support unlimited, as best I can tell).
